[package]
name = "eww-widget"
edition = "2024"

[[bin]]
name = "niri-workspace"
path = "niri-workspace.rs"

[[bin]]
name = "battery"
path = "battery.rs"

[[bin]]
name = "volume"
path = "volume.rs"

[dependencies]
# basic
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

# niri ipc
indexmap = { version = "1", features = [ "serde" ] }
niri-ipc = { git = "https://github.com/YaLTeR/niri" }

# battery
starship-battery = "0.10"

