theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
";" = "command_mode"
"a" = "insert_at_line_end"
"A" = "append_mode"
"C-o" = "buffer_picker"

# search
"*" = [
	"move_char_right",
	"move_prev_word_start",
	"move_next_word_end",
	"search_selection",
]

# window
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"

[keys.normal.","]
"," = "keep_primary_selection"
"n" = "file_picker_in_current_directory"
"q" = "wclose"

[keys.insert]
"A-space" = "normal_mode"
