theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
";" = "command_mode"
"C-o" = "buffer_picker"

"A-n" = "goto_prev_paragraph"
"A-m" = "goto_next_paragraph"

# search
"*" = "@miw,s<ret>"

# window
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"

[keys.normal.","]
"," = [ "collapse_selection", "keep_primary_selection" ] # clear select
"n" = "file_picker_in_current_directory"
"q" = "wclose"
"f" = "@maf<A-;>,," # jump to function header
"s" = "search_selection"

[keys.normal."d"]
"d" = [ "extend_to_line_bounds", "delete_selection" ]

[keys.insert]
"A-space" = "normal_mode"

[keys.select]
"p" = [ "delete_selection_noyank", "paste_before" ]

[keys.select.","]
"," = [ "collapse_selection", "keep_primary_selection", "normal_mode" ]
