theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
auto-format = false
color-modes = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
";" = "command_mode"
"C-o" = "buffer_picker"

# search
"*" = [
	"move_char_right",
	"move_prev_word_start",
	"move_next_word_end",
	"search_selection",
]

# window
"A-h" = "jump_view_left"
"A-j" = "jump_view_down"
"A-k" = "jump_view_up"
"A-l" = "jump_view_right"

[keys.normal.","]
"," = [ "collapse_selection", "keep_primary_selection" ] # clear select
"n" = "file_picker_in_current_directory"
"q" = "wclose"
"f" = "@:hs<ret><A-k>maf<A-;>,," # jump to function header

[keys.normal."d"]
"d" = [ "extend_to_line_bounds", "delete_selection" ]

[keys.insert]
"A-space" = "normal_mode"

[keys.select]
"p" = [ "delete_selection_noyank", "paste_before" ]

[keys.select.","]
"," = [ "collapse_selection", "keep_primary_selection", "normal_mode" ]
