#!/usr/bin/sh

cat << EOF
{
	"set-env": {
		"EDITOR": "helix"
	},
	"push-path": [
		"$HOME/.local/bin",
		"$HOME/.cargo/bin"
	],
	"prompt": {
		"exe": "starship",
		"args": ["prompt", "-s", "@status", "-w", "@width"]
	},
	"complete": {
		"exe": "fish-as-a-complete-engine",
		"args": ["-i", "@index"]
	},
	"alias": {
		"ls": ["eza"],
		"la": ["eza", "-hal"],
		"hx": ["helix"],
		"wget": ["curl", "-L", "-O", "-C", "-"]
	}
}
EOF
