[package]
name = "niri-workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
indexmap = { version = "1", features = [ "serde" ] }
niri-ipc = { git = "https://github.com/YaLTeR/niri" }
